#!/usr/bin/env sh

## antibody
alias ain="curl -sL git.io/antibody | sh -s" # install antibody simple way - [A]ntibody [IN]stall
alias abp="antibody bundle < ~/.antibody.txt > ~/.antibody.sh" # [A]ntibody [B]undle [P]lugins
alias aup="antibody update" # [A]ntibody [UP]date

## git
alias ggc="git-config-template" # [G]it [G]enerate [C]onfig
alias gco="git-fzy-checkout"
alias gcofzf="git-fzf-checkout" # [G]it [C]heck[O]ut
alias gbd="git-fzf-branch -m -D" # [G]it [B]ranch [D]elete
alias gtg="git-fzf-tag +m" # [G]it [T]ags
alias gtd="git-fzf-tag -m -d" # [G]it [T]ag [D]elete

## pacman/yay
alias pacss="sudo pacman-fzf" # pacman -Ss
alias pacin="sudo pacman-fzf -S" # pacman -S
alias yayss="yay-fzf" # yay -Ss
alias yayin="yay-fzf -S" # yay -S

## manipulate files
alias cat="bat"
alias nvgit="nvim-git-fzf"
