AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Metrics/LineLength:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
