#! /bin/sh

WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S %p"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}
POSITION=${POSITION:-"top"}
BLOCK_WIDTH=${BLOCK_WIDTH:-25}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

	# the position of the upper right corner of the popup
	_COLUMNS=$(tput cols)
	_LINES=$(tput lines)
	posX=$(($_LINES - ${#WIDTH}))
	[[ $POSITION == 'top' ]] && \
		posY=$((- ($_COLUMNS - ${#HEIGHT}) + $BLOCK_WIDTH )) || \
		posY=$((($_COLUMNS - ${#HEIGHT}) + $BLOCK_WIDTH ))

	i3-msg -q "exec yad --calendar \
        --width=$WIDTH --height=$HEIGHT \
	    --undecorated --fixed \
	    --close-on-unfocus --no-buttons \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac
echo "$LABEL$(date "$DATEFMT")"
echo "$LABEL$(date "$SHORTFMT")"
