#!/usr/bin/env bash
# Install one or more versions of specified language
# Mnemonic [L]ang [M]anager [I]nstall
lang="$1"

if [[ "$lang" == '' ]]; then
	lang=$(asdf plugin-list | fzf)
fi

if [[ "$lang" != '' ]]; then
	versions=$(asdf list-all "$lang" | fzf -m)
	if [[ "$versions" ]]; then
	  for version in $(echo "$versions"); do
		  asdf install "$lang" "$version"
	  done
	fi
fi
