#!/usr/bin/env bash
# Remove one or more versions of specified language
# Mnemonic [L]ang [M]anager [C]lean
lang="$1"

if [[ "$lang" == '' ]]; then
	lang=$(asdf plugin-list | fzf)
fi

if [[ "$lang" != '' ]]; then
	versions=$(asdf list "$lang" | fzf -m)
	if [[ "$versions" ]]; then
	  for version in $(echo "$versions"); do
		  asdf uninstall "$lang" "$version"
	  done
	fi
fi
