#!/usr/bin/env bash
# Remove a plugin of specified language
# lang manager plugin clean
lang="$1"

if [[ "$lang" == '' ]]; then
	lang=$(asdf plugin-list | fzf)
	asdf plugin-remove "$lang"
	exit 1
fi

if [[ "$lang" != '' ]]; then
	plugin_url=$(asdf plugin-list | fzf --query="'$lang" -m)
	asdf plugin-remove "$plugin_url"
fi
