#!/usr/bin/env bash
# git-tags - checkout git branch (including remote branches)

function _fzf() {
  fzf --cycle --height=80% "$@"
}

## Test if is into a git repository.
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "fatal: Not a git repo!"
  exit 1
fi

if [[ "$(git --no-pager tag)" == '' ]]; then 
  echo "git-fzf-tag: no tags" 
  exit 1
fi

## Get all tags and drop it into a FZF list.
# git log format:
# %h - abreviatted commit hash
# %s - subject
# %an - author name
git --no-pager tag \
  | _fzf +s "$1" +e --no-hscroll --ansi -d '\t' -n 2 --preview-window 'right:70%' \
  --preview 'git log --graph --color --pretty=tformat:"%C(yellow)%h %Creset%s - %Cgreen%an%Creset" --date=human {1} -- | head -200'
